# Generated by Django 4.2.4 on 2023-08-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons_app_person',
        ),
    ]
